version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - app.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  # redis:
  #   image: redis:7-alpine
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    env_file:
      - app.env
    environment:
      - DB_HOST=postgres
      # - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    #   - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      # - redis
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
volumes:
  data-volume:
