// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"time"
)

type Task struct {
	ID        int64     `json:"id"`
	Body      string    `json:"body"`
	IsDone    bool      `json:"isDone"`
	OwnerID   int64     `json:"ownerId"`
	CreatedAt time.Time `json:"createdAt"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashedPassword"`
	PasswordChangedAt time.Time `json:"passwordChangedAt"`
	CreatedAt         time.Time `json:"createdAt"`
}
