// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetTask(ctx context.Context, id int64) (Task, error)
	GetTaskList(ctx context.Context, arg GetTaskListParams) ([]Task, error)
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
